/**
 * This file is auto-generated by scripts/generate-yahoo-finance-schemas.ts
 * DO NOT EDIT MANUALLY - Run 'pnpm generate:schemas' to regenerate
 *
 * Generated from: lib/models/yahoo-finance-types.ts
 * Generated at: 2025-11-16T23:12:59.621Z
 */

// Generated by ts-to-zod
import { z } from "zod";

const _dateInMsSchema = z.number();

export const defaultKeyStatisticsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    priceHint: z.number(),
    enterpriseValue: z.number().optional(),
    forwardPE: z.number().optional(),
    profitMargins: z.number().optional(),
    floatShares: z.number().optional(),
    sharesOutstanding: z.number().optional(),
    sharesShort: z.number().optional(),
    sharesShortPriorMonth: z.string().optional(),
    sharesShortPreviousMonthDate: z.string().optional(),
    dateShortInterest: z.string().optional(),
    sharesPercentSharesOut: z.number().optional(),
    heldPercentInsiders: z.number().optional(),
    heldPercentInstitutions: z.number().optional(),
    shortRatio: z.number().optional(),
    shortPercentOfFloat: z.number().optional(),
    beta: z.number().optional(),
    impliedSharesOutstanding: z.number().optional(),
    category: z.string().nullable(),
    bookValue: z.number().optional(),
    priceToBook: z.number().optional(),
    fundFamily: z.string().nullable(),
    legalType: z.string().nullable(),
    lastFiscalYearEnd: z.string().optional(),
    nextFiscalYearEnd: z.string().optional(),
    mostRecentQuarter: z.string().optional(),
    earningsQuarterlyGrowth: z.number().optional(),
    netIncomeToCommon: z.number().optional(),
    trailingEps: z.number().optional(),
    forwardEps: z.number().optional(),
    pegRatio: z.number().optional(),
    lastSplitFactor: z.string().nullable(),
    lastSplitDate: z.number().optional(),
    enterpriseToRevenue: z.number().optional(),
    enterpriseToEbitda: z.number().optional(),
    "52WeekChange": z.number().optional(),
    SandP52WeekChange: z.number().optional(),
    lastDividendValue: z.number().optional(),
    lastDividendDate: z.string().optional(),
    ytdReturn: z.number().optional(),
    beta3Year: z.number().optional(),
    totalAssets: z.number().optional(),
    yield: z.number().optional(),
    fundInceptionDate: z.string().optional(),
    threeYearAverageReturn: z.number().optional(),
    fiveYearAverageReturn: z.number().optional(),
    morningStarOverallRating: z.number().optional(),
    morningStarRiskRating: z.number().optional(),
    annualReportExpenseRatio: z.number().optional(),
    lastCapGain: z.number().optional(),
    annualHoldingsTurnover: z.number().optional(),
    latestShareClass: z.unknown().optional(),
    leadInvestor: z.unknown().optional(),
  })
);

export const financialDataSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    currentPrice: z.number().optional(),
    targetHighPrice: z.number().optional(),
    targetLowPrice: z.number().optional(),
    targetMeanPrice: z.number().optional(),
    targetMedianPrice: z.number().optional(),
    recommendationMean: z.number().optional(),
    recommendationKey: z.string(),
    numberOfAnalystOpinions: z.number().optional(),
    totalCash: z.number().optional(),
    totalCashPerShare: z.number().optional(),
    ebitda: z.number().optional(),
    totalDebt: z.number().optional(),
    quickRatio: z.number().optional(),
    currentRatio: z.number().optional(),
    totalRevenue: z.number().optional(),
    debtToEquity: z.number().optional(),
    revenuePerShare: z.number().optional(),
    returnOnAssets: z.number().optional(),
    returnOnEquity: z.number().optional(),
    grossProfits: z.number().optional(),
    freeCashflow: z.number().optional(),
    operatingCashflow: z.number().optional(),
    earningsGrowth: z.number().optional(),
    revenueGrowth: z.number().optional(),
    grossMargins: z.number().optional(),
    ebitdaMargins: z.number().optional(),
    operatingMargins: z.number().optional(),
    profitMargins: z.number().optional(),
    financialCurrency: z.string().nullable(),
  })
);

export const trendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    symbol: z.null(),
    estimates: z.array(z.unknown()),
  })
);

export const majorHoldersBreakdownSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      maxAge: z.number(),
      insidersPercentHeld: z.number().optional(),
      institutionsPercentHeld: z.number().optional(),
      institutionsFloatPercentHeld: z.number().optional(),
      institutionsCount: z.number().optional(),
    })
  );

export const netSharePurchaseActivitySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      maxAge: z.number(),
      period: z.string(),
      buyInfoCount: z.number(),
      buyInfoShares: z.number(),
      buyPercentInsiderShares: z.number().optional(),
      sellInfoCount: z.number(),
      sellInfoShares: z.number().optional(),
      sellPercentInsiderShares: z.number().optional(),
      netInfoCount: z.number(),
      netInfoShares: z.number(),
      netPercentInsiderShares: z.number().optional(),
      totalInsiderShares: z.number(),
    })
  );

export const priceSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    averageDailyVolume10Day: z.number().optional(),
    averageDailyVolume3Month: z.number().optional(),
    exchange: z.string().optional(),
    exchangeName: z.string().optional(),
    exchangeDataDelayedBy: z.number().optional(),
    maxAge: z.number(),
    postMarketChangePercent: z.number().optional(),
    postMarketChange: z.number().optional(),
    postMarketTime: z.string().optional(),
    postMarketPrice: z.number().optional(),
    postMarketSource: z.string().optional(),
    preMarketChangePercent: z.number().optional(),
    preMarketChange: z.number().optional(),
    preMarketTime: z.string().optional(),
    preMarketPrice: z.number().optional(),
    preMarketSource: z.string().optional(),
    priceHint: z.number(),
    regularMarketChangePercent: z.number().optional(),
    regularMarketChange: z.number().optional(),
    regularMarketTime: z.string().optional(),
    regularMarketPrice: z.number().optional(),
    regularMarketDayHigh: z.number().optional(),
    regularMarketDayLow: z.number().optional(),
    regularMarketVolume: z.number().optional(),
    regularMarketPreviousClose: z.number().optional(),
    regularMarketSource: z.string().optional(),
    regularMarketOpen: z.number().optional(),
    quoteSourceName: z.string().optional(),
    quoteType: z.string(),
    symbol: z.string(),
    underlyingSymbol: z.string().nullable(),
    shortName: z.string().nullable(),
    longName: z.string().nullable(),
    lastMarket: z.string().nullable(),
    marketState: z.string().optional(),
    marketCap: z.number().optional(),
    currency: z.string().optional(),
    currencySymbol: z.string().optional(),
    fromCurrency: z.string().nullable(),
    toCurrency: z.string().optional().nullable(),
    volume24Hr: z.number().optional(),
    volumeAllCurrencies: z.number().optional(),
    circulatingSupply: z.number().optional(),
    expireDate: z.string().optional(),
    openInterest: z.number().optional(),
  })
);

export const quoteTypeSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    exchange: z.string(),
    quoteType: z.string(),
    symbol: z.string(),
    underlyingSymbol: z.string(),
    shortName: z.string().nullable(),
    longName: z.string().optional().nullable(),
    firstTradeDateEpochUtc: z.string().optional().nullable(),
    timeZoneFullName: z.string(),
    timeZoneShortName: z.string(),
    uuid: z.string(),
    messageBoardId: z.string().optional().nullable(),
    gmtOffSetMilliseconds: z.number(),
    maxAge: z.number(),
  })
);

export const summaryDetailSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    priceHint: z.number(),
    previousClose: z.number().optional(),
    open: z.number().optional(),
    dayLow: z.number().optional(),
    dayHigh: z.number().optional(),
    regularMarketPreviousClose: z.number().optional(),
    regularMarketOpen: z.number().optional(),
    regularMarketDayLow: z.number().optional(),
    regularMarketDayHigh: z.number().optional(),
    regularMarketVolume: z.number().optional(),
    dividendRate: z.number().optional(),
    dividendYield: z.number().optional(),
    exDividendDate: z.string().optional(),
    payoutRatio: z.number().optional(),
    fiveYearAvgDividendYield: z.number().optional(),
    beta: z.number().optional(),
    trailingPE: z.number().optional(),
    forwardPE: z.number().optional(),
    volume: z.number().optional(),
    averageVolume: z.number().optional(),
    averageVolume10days: z.number().optional(),
    averageDailyVolume10Day: z.number().optional(),
    bid: z.number().optional(),
    ask: z.number().optional(),
    bidSize: z.number().optional(),
    askSize: z.number().optional(),
    marketCap: z.number().optional(),
    fiftyDayAverage: z.number().optional(),
    fiftyTwoWeekLow: z.number().optional(),
    fiftyTwoWeekHigh: z.number().optional(),
    twoHundredDayAverage: z.number().optional(),
    priceToSalesTrailing12Months: z.number().optional(),
    trailingAnnualDividendRate: z.number().optional(),
    trailingAnnualDividendYield: z.number().optional(),
    currency: z.string(),
    algorithm: z.null(),
    tradeable: z.boolean(),
    yield: z.number().optional(),
    totalAssets: z.number().optional(),
    navPrice: z.number().optional(),
    ytdReturn: z.number().optional(),
    fromCurrency: z.string().nullable(),
    toCurrency: z.string().optional().nullable(),
    lastMarket: z.string().nullable(),
    volume24Hr: z.number().optional(),
    volumeAllCurrencies: z.number().optional(),
    circulatingSupply: z.number().optional(),
    startDate: z.string().optional(),
    coinMarketCapLink: z.string().optional().nullable(),
    expireDate: z.string().optional(),
    openInterest: z.number().optional(),
    averageMaturity: z.number().optional(),
  })
);

export const summaryProfileSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    address1: z.string().optional(),
    address2: z.string().optional(),
    address3: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    country: z.string().optional(),
    phone: z.string().optional(),
    fax: z.string().optional(),
    website: z.string().optional(),
    industry: z.string().optional(),
    industryDisp: z.string().optional(),
    sector: z.string().optional(),
    sectorDisp: z.string().optional(),
    longBusinessSummary: z.string().optional(),
    fullTimeEmployees: z.number().optional(),
    companyOfficers: z.array(z.unknown()),
    maxAge: z.number(),
    twitter: z.string().optional(),
    industryKey: z.string().optional(),
    sectorKey: z.string().optional(),
    irWebsite: z.string().optional(),
    executiveTeam: z.array(z.unknown()).optional(),
    name: z.string().optional(),
    startDate: z.string().optional(),
    description: z.string().optional(),
  })
);

export const companyOfficerSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    name: z.string(),
    age: z.number().optional(),
    title: z.string(),
    yearBorn: z.number().optional(),
    fiscalYear: z.number().optional(),
    totalPay: z.number().optional(),
    exercisedValue: z.number().optional(),
    unexercisedValue: z.number().optional(),
  })
);

export const balanceSheetStatementSchema = z.object({
  maxAge: z.number(),
  endDate: z.string(),
});

export const calendarEventsEarningsSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      earningsCallDate: z.array(z.string()),
      isEarningsDateEstimate: z.boolean().optional(),
      earningsDate: z.array(z.string()),
      earningsAverage: z.number().optional(),
      earningsLow: z.number().optional(),
      earningsHigh: z.number().optional(),
      revenueAverage: z.number().optional(),
      revenueLow: z.number().optional(),
      revenueHigh: z.number().optional(),
    })
  );

export const cashflowStatementSchema = z.object({
  maxAge: z.number(),
  endDate: z.string(),
  netIncome: z.number(),
});

export const earningsChartQuarterlySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      date: z.string(),
      actual: z.number().optional(),
      estimate: z.number(),
    })
  );

export const yearlySchema = z.record(z.string(), z.unknown()).and(
  z.object({
    date: z.number(),
    revenue: z.number(),
    earnings: z.number(),
  })
);

export const financialsChartQuarterlySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      date: z.string(),
      revenue: z.number(),
      earnings: z.number(),
    })
  );

export const earningsHistoryHistorySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      maxAge: z.number(),
      epsActual: z.number().nullable(),
      epsEstimate: z.number().nullable(),
      epsDifference: z.number().nullable(),
      surprisePercent: z.number().nullable(),
      quarter: z.string().nullable(),
      period: z.string(),
      currency: z.string().optional(),
    })
  );

export const earningsEstimateSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    avg: z.number().nullable(),
    low: z.number().nullable(),
    high: z.number().nullable(),
    yearAgoEps: z.number().nullable(),
    numberOfAnalysts: z.number().nullable(),
    growth: z.number().nullable(),
    earningsCurrency: z.string().optional().nullable(),
  })
);

export const revenueEstimateSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    avg: z.number().nullable(),
    low: z.number().nullable(),
    high: z.number().nullable(),
    numberOfAnalysts: z.number().nullable(),
    yearAgoRevenue: z.number().nullable(),
    growth: z.number().nullable(),
    revenueCurrency: z.string().optional().nullable(),
  })
);

export const epsTrendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    current: z.number().nullable(),
    "7daysAgo": z.number().nullable(),
    "30daysAgo": z.number().nullable(),
    "60daysAgo": z.number().nullable(),
    "90daysAgo": z.number().nullable(),
    epsTrendCurrency: z.string().optional().nullable(),
  })
);

export const epsRevisionsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    upLast7days: z.number().optional().nullable(),
    upLast30days: z.number().optional().nullable(),
    upLast90days: z.number().optional().nullable(),
    downLast7Days: z.number().optional().nullable(),
    downLast30days: z.number().optional().nullable(),
    downLast90days: z.number().optional().nullable(),
    epsRevisionsCurrency: z.string().optional().nullable(),
  })
);

export const ownershipListSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    reportDate: z.string(),
    organization: z.string(),
    pctHeld: z.number(),
    position: z.number(),
    value: z.number(),
    pctChange: z.number().optional(),
  })
);

export const periodRangeSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    asOfDate: z.string().optional(),
    ytd: z.number().optional(),
    oneMonth: z.number().optional(),
    threeMonth: z.number().optional(),
    oneYear: z.number().optional(),
    threeYear: z.number().optional(),
    fiveYear: z.number().optional(),
    tenYear: z.number().optional(),
  })
);

export const fundPerformancePerformanceOverviewSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      asOfDate: z.string().optional(),
      ytdReturnPct: z.number().optional(),
      oneYearTotalReturn: z.number().optional(),
      threeYearTotalReturn: z.number().optional(),
      fiveYrAvgReturnPct: z.number().optional(),
      morningStarReturnRating: z.number().optional(),
      numYearsUp: z.number().optional(),
      numYearsDown: z.number().optional(),
      bestOneYrTotalReturn: z.number().optional(),
      worstOneYrTotalReturn: z.number().optional(),
      bestThreeYrTotalReturn: z.number().optional(),
      worstThreeYrTotalReturn: z.number().optional(),
    })
  );

export const fundPerformancePerformanceOverviewCatSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      ytdReturnPct: z.number().optional(),
      fiveYrAvgReturnPct: z.number().optional(),
      oneYearTotalReturn: z.number().optional(),
      threeYearTotalReturn: z.number().optional(),
    })
  );

export const fundPerformanceTrailingReturnsSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      asOfDate: z.string().optional(),
      ytd: z.number().optional(),
      oneMonth: z.number().optional(),
      threeMonth: z.number().optional(),
      oneYear: z.number().optional(),
      threeYear: z.number().optional(),
      fiveYear: z.number().optional(),
      tenYear: z.number().optional(),
      lastBullMkt: z.number().optional(),
      lastBearMkt: z.number().optional(),
    })
  );

export const fundPerformanceReturnsRowSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      year: z.number(),
      annualValue: z.number().optional(),
      q1: z.number().optional(),
      q2: z.number().optional(),
      q3: z.number().optional(),
      q4: z.number().optional(),
    })
  );

export const fundPerformanceRiskOverviewStatsRowSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      year: z.string(),
      alpha: z.number(),
      beta: z.number(),
      meanAnnualReturn: z.number(),
      rSquared: z.number(),
      stdDev: z.number().optional(),
      sharpeRatio: z.number(),
      treynorRatio: z.number(),
    })
  );

export const fundPerformanceRiskOverviewStatsCatSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      riskStatisticsCat: z.array(fundPerformanceRiskOverviewStatsRowSchema),
    })
  );

export const fundProfileManagementInfoSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      managerName: z.string().nullable(),
      managerBio: z.string().nullable(),
      startdate: z.string().optional(),
    })
  );

export const fundProfileFeesExpensesInvestmentSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      annualHoldingsTurnover: z.number().optional(),
      annualReportExpenseRatio: z.number().optional(),
      grossExpRatio: z.number().optional(),
      netExpRatio: z.number().optional(),
      projectionValues: z.record(z.string(), z.any()),
      totalNetAssets: z.number().optional(),
    })
  );

export const fundProfileBrokerageSchema = z.record(z.string(), z.unknown());

export const fundProfileSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    styleBoxUrl: z.string().nullable().optional(),
    family: z.string().nullable(),
    categoryName: z.string().nullable(),
    legalType: z.string().nullable(),
    managementInfo: fundProfileManagementInfoSchema.optional(),
    feesExpensesInvestment: fundProfileFeesExpensesInvestmentSchema.optional(),
    feesExpensesInvestmentCat: z
      .record(z.string(), z.unknown())
      .and(
        z.object({
          projectionValuesCat: z.record(z.string(), z.any()),
        })
      )
      .optional(),
    brokerages: z.array(fundProfileBrokerageSchema).optional(),
    initInvestment: z.number().optional(),
    initIraInvestment: z.number().optional(),
    initAipInvestment: z.number().optional(),
    subseqInvestment: z.number().optional(),
    subseqIraInvestment: z.number().optional(),
    subseqAipInvestment: z.number().optional(),
  })
);

export const incomeStatementHistoryElementSchema = z.object({
  maxAge: z.number(),
  endDate: z.string(),
  totalRevenue: z.number(),
  costOfRevenue: z.number(),
  grossProfit: z.number(),
  researchDevelopment: z.null(),
  sellingGeneralAdministrative: z.null(),
  nonRecurring: z.null(),
  otherOperatingExpenses: z.null(),
  totalOperatingExpenses: z.number(),
  operatingIncome: z.null(),
  totalOtherIncomeExpenseNet: z.null(),
  ebit: z.number(),
  interestExpense: z.null(),
  incomeBeforeTax: z.null(),
  incomeTaxExpense: z.number(),
  minorityInterest: z.null(),
  netIncomeFromContinuingOps: z.null(),
  discontinuedOperations: z.null(),
  extraordinaryItems: z.null(),
  effectOfAccountingCharges: z.null(),
  otherItems: z.null(),
  netIncome: z.number(),
  netIncomeApplicableToCommonShares: z.null(),
});

export const estimateSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    period: z.string(),
    growth: z.number().optional(),
  })
);

export const relationSchema = z.enum([
  "Chairman of the Board",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Operating Officer",
  "Chief Technology Officer",
  "Director",
  "Director (Independent)",
  "",
  "General Counsel",
  "Independent Non-Executive Director",
  "Officer",
  "President",
] as const);

export const ownershipEnumSchema = z.enum(["D", "I"] as const);

export const recommendationTrendTrendSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      period: z.string(),
      strongBuy: z.number(),
      buy: z.number(),
      hold: z.number(),
      sell: z.number(),
      strongSell: z.number(),
    })
  );

const filingTypeSchema = z.union([
  z.literal("10-K"),
  z.literal("10-Q"),
  z.literal("8-K"),
  z.literal("8-K/A"),
  z.literal("10-K/A"),
  z.literal("10-Q/A"),
  z.literal("SD"),
  z.literal("PX14A6G"),
  z.literal("SC 13G/A"),
  z.literal("DEFA14A"),
  z.literal("25-NSE"),
  z.literal("S-8 POS"),
  z.literal("6-K"),
  z.literal("F-3ASR"),
  z.literal("SC 13D/A"),
  z.literal("20-F"),
  z.literal("425"),
  z.literal("SC14D9C"),
  z.literal("SC 13G"),
  z.literal("S-8"),
  z.literal("DEF 14A"),
  z.literal("F-10"),
  z.literal("S-3ASR"),
  z.literal("CORRESP"),
  z.literal("PX14A6N"),
  z.literal("N-PX"),
  z.literal("ARS"),
  z.literal("PRE 14A"),
  z.literal("F-6EF"),
  z.literal("S-3/A"),
  z.literal("S-3"),
  z.literal("POS AM"),
  z.literal("IRANNOTICE"),
  z.literal("20-F/A"),
  z.literal("11-K"),
  z.literal("DEFR14A"),
]);

export const topHoldingsHoldingSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    symbol: z.string(),
    holdingName: z.string(),
    holdingPercent: z.number(),
  })
);

export const topHoldingsEquityHoldingsSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      medianMarketCap: z.number().optional(),
      medianMarketCapCat: z.number().optional(),
      priceToBook: z.number(),
      priceToBookCat: z.number().optional(),
      priceToCashflow: z.number(),
      priceToCashflowCat: z.number().optional(),
      priceToEarnings: z.number(),
      priceToEarningsCat: z.number().optional(),
      priceToSales: z.number(),
      priceToSalesCat: z.number().optional(),
      threeYearEarningsGrowth: z.number().optional(),
      threeYearEarningsGrowthCat: z.number().optional(),
    })
  );

export const topHoldingsBondRatingSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      a: z.number().optional(),
      aa: z.number().optional(),
      aaa: z.number().optional(),
      other: z.number().optional(),
      b: z.number().optional(),
      bb: z.number().optional(),
      bbb: z.number().optional(),
      below_b: z.number().optional(),
      us_government: z.number().optional(),
    })
  );

export const topHoldingsSectorWeightingSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      realestate: z.number().optional(),
      consumer_cyclical: z.number().optional(),
      basic_materials: z.number().optional(),
      consumer_defensive: z.number().optional(),
      technology: z.number().optional(),
      communication_services: z.number().optional(),
      financial_services: z.number().optional(),
      utilities: z.number().optional(),
      industrials: z.number().optional(),
      energy: z.number().optional(),
      healthcare: z.number().optional(),
    })
  );

export const gradeSchema = z.enum([
  "Accumulate",
  "Add",
  "Average",
  "Below Average",
  "Buy",
  "Conviction Buy",
  "",
  "Equal-Weight",
  "Fair Value",
  "Equal-weight",
  "Long-term Buy",
  "Hold",
  "Long-Term Buy",
  "Market Outperform",
  "Market Perform",
  "Mixed",
  "Negative",
  "Neutral",
  "In-Line",
  "Outperform",
  "Overweight",
  "Peer Perform",
  "Perform",
  "Positive",
  "Reduce",
  "Sector Outperform",
  "Sector Perform",
  "Sector Weight",
  "Sell",
  "Strong Buy",
  "Top Pick",
  "Underperform",
  "Underperformer",
  "Underweight",
  "Trim",
  "Above Average",
  "In-line",
  "Outperformer",
  "OVerweight",
  "Cautious",
  "Market Weight",
  "Sector Underperform",
  "Market Underperform",
  "Peer perform",
  "Gradually Accumulate",
  "Action List Buy",
  "Performer",
  "Sector Performer",
  "Speculative Buy",
  "Strong Sell",
  "Speculative Hold",
  "Not Rated",
  "Hold Neutral",
  "Developing",
  "buy",
  "HOld",
  "Trading Sell",
  "Tender",
  "market perform",
  "BUy",
] as const);

export const actionSchema = z.enum([
  "down",
  "init",
  "main",
  "reit",
  "up",
] as const);

export const fundamentalsTimeSeriesPeriodSchema = z.union([
  z.literal("3M"),
  z.literal("12M"),
]);

export const fundamentalsTimeSeriesFinancialsResultSchema = z.object({
  date: z.string(),
  TYPE: z.literal("FINANCIALS"),
  periodType: fundamentalsTimeSeriesPeriodSchema,
  totalRevenue: z.number().optional(),
  operatingRevenue: z.number().optional(),
  costOfRevenue: z.number().optional(),
  grossProfit: z.number().optional(),
  sellingGeneralAndAdministration: z.number().optional(),
  sellingAndMarketingExpense: z.number().optional(),
  generalAndAdministrativeExpense: z.number().optional(),
  otherGandA: z.number().optional(),
  researchAndDevelopment: z.number().optional(),
  depreciationAmortizationDepletionIncomeStatement: z.number().optional(),
  depletionIncomeStatement: z.number().optional(),
  depreciationAndAmortizationInIncomeStatement: z.number().optional(),
  amortization: z.number().optional(),
  amortizationOfIntangiblesIncomeStatement: z.number().optional(),
  depreciationIncomeStatement: z.number().optional(),
  otherOperatingExpenses: z.number().optional(),
  operatingExpense: z.number().optional(),
  operatingIncome: z.number().optional(),
  interestExpenseNonOperating: z.number().optional(),
  interestIncomeNonOperating: z.number().optional(),
  totalOtherFinanceCost: z.number().optional(),
  netNonOperatingInterestIncomeExpense: z.number().optional(),
  writeOff: z.number().optional(),
  specialIncomeCharges: z.number().optional(),
  gainOnSaleOfPPE: z.number().optional(),
  gainOnSaleOfBusiness: z.number().optional(),
  gainOnSaleOfSecurity: z.number().optional(),
  otherSpecialCharges: z.number().optional(),
  otherIncomeExpense: z.number().optional(),
  otherNonOperatingIncomeExpenses: z.number().optional(),
  totalExpenses: z.number().optional(),
  pretaxIncome: z.number().optional(),
  taxProvision: z.number().optional(),
  netIncomeContinuousOperations: z.number().optional(),
  netIncomeIncludingNoncontrollingInterests: z.number().optional(),
  minorityInterests: z.number().optional(),
  netIncomeFromTaxLossCarryforward: z.number().optional(),
  netIncomeExtraordinary: z.number().optional(),
  netIncomeDiscontinuousOperations: z.number().optional(),
  preferredStockDividends: z.number().optional(),
  otherunderPreferredStockDividend: z.number().optional(),
  netIncomeCommonStockholders: z.number().optional(),
  netIncome: z.number().optional(),
  basicAverageShares: z.number().optional(),
  dilutedAverageShares: z.number().optional(),
  dividendPerShare: z.number().optional(),
  reportedNormalizedBasicEPS: z.number().optional(),
  continuingAndDiscontinuedBasicEPS: z.number().optional(),
  basicEPSOtherGainsLosses: z.number().optional(),
  taxLossCarryforwardBasicEPS: z.number().optional(),
  normalizedBasicEPS: z.number().optional(),
  basicEPS: z.number().optional(),
  basicAccountingChange: z.number().optional(),
  basicExtraordinary: z.number().optional(),
  basicDiscontinuousOperations: z.number().optional(),
  basicContinuousOperations: z.number().optional(),
  reportedNormalizedDilutedEPS: z.number().optional(),
  continuingAndDiscontinuedDilutedEPS: z.number().optional(),
  taxLossCarryforwardDilutedEPS: z.number().optional(),
  averageDilutionEarnings: z.number().optional(),
  normalizedDilutedEPS: z.number().optional(),
  dilutedEPS: z.number().optional(),
  dilutedAccountingChange: z.number().optional(),
  dilutedExtraordinary: z.number().optional(),
  dilutedContinuousOperations: z.number().optional(),
  dilutedDiscontinuousOperations: z.number().optional(),
  dilutedNIAvailtoComStockholders: z.number().optional(),
  dilutedEPSOtherGainsLosses: z.number().optional(),
  totalOperatingIncomeAsReported: z.number().optional(),
  netIncomeFromContinuingAndDiscontinuedOperation: z.number().optional(),
  normalizedIncome: z.number().optional(),
  netInterestIncome: z.number().optional(),
  EBIT: z.number().optional(),
  EBITDA: z.number().optional(),
  reconciledCostOfRevenue: z.number().optional(),
  reconciledDepreciation: z.number().optional(),
  netIncomeFromContinuingOperationNetMinorityInterest: z.number().optional(),
  totalUnusualItemsExcludingGoodwill: z.number().optional(),
  totalUnusualItems: z.number().optional(),
  normalizedEBITDA: z.number().optional(),
  taxRateForCalcs: z.number().optional(),
  taxEffectOfUnusualItems: z.number().optional(),
  rentExpenseSupplemental: z.number().optional(),
  earningsFromEquityInterestNetOfTax: z.number().optional(),
  impairmentOfCapitalAssets: z.number().optional(),
  restructuringAndMergernAcquisition: z.number().optional(),
  securitiesAmortization: z.number().optional(),
  earningsFromEquityInterest: z.number().optional(),
  otherTaxes: z.number().optional(),
  provisionForDoubtfulAccounts: z.number().optional(),
  insuranceAndClaims: z.number().optional(),
  rentAndLandingFees: z.number().optional(),
  salariesAndWages: z.number().optional(),
  exciseTaxes: z.number().optional(),
  interestExpense: z.number().optional(),
  interestIncome: z.number().optional(),
  totalMoneyMarketInvestments: z.number().optional(),
  interestIncomeAfterProvisionForLoanLoss: z.number().optional(),
  otherThanPreferredStockDividend: z.number().optional(),
  lossonExtinguishmentofDebt: z.number().optional(),
  incomefromAssociatesandOtherParticipatingInterests: z.number().optional(),
  nonInterestExpense: z.number().optional(),
  otherNonInterestExpense: z.number().optional(),
  professionalExpenseAndContractServicesExpense: z.number().optional(),
  occupancyAndEquipment: z.number().optional(),
  equipment: z.number().optional(),
  netOccupancyExpense: z.number().optional(),
  creditLossesProvision: z.number().optional(),
  nonInterestIncome: z.number().optional(),
  otherNonInterestIncome: z.number().optional(),
  gainLossonSaleofAssets: z.number().optional(),
  gainonSaleofInvestmentProperty: z.number().optional(),
  gainonSaleofLoans: z.number().optional(),
  foreignExchangeTradingGains: z.number().optional(),
  tradingGainLoss: z.number().optional(),
  investmentBankingProfit: z.number().optional(),
  dividendIncome: z.number().optional(),
  feesAndCommissions: z.number().optional(),
  feesandCommissionExpense: z.number().optional(),
  feesandCommissionIncome: z.number().optional(),
  otherCustomerServices: z.number().optional(),
  creditCard: z.number().optional(),
  securitiesActivities: z.number().optional(),
  trustFeesbyCommissions: z.number().optional(),
  serviceChargeOnDepositorAccounts: z.number().optional(),
  totalPremiumsEarned: z.number().optional(),
  otherInterestExpense: z.number().optional(),
  interestExpenseForFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell:
    z.number().optional(),
  interestExpenseForLongTermDebtAndCapitalSecurities: z.number().optional(),
  interestExpenseForShortTermDebt: z.number().optional(),
  interestExpenseForDeposit: z.number().optional(),
  otherInterestIncome: z.number().optional(),
  interestIncomeFromFederalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell:
    z.number().optional(),
  interestIncomeFromDeposits: z.number().optional(),
  interestIncomeFromSecurities: z.number().optional(),
  interestIncomeFromLoansAndLease: z.number().optional(),
  interestIncomeFromLeases: z.number().optional(),
  interestIncomeFromLoans: z.number().optional(),
  depreciationDepreciationIncomeStatement: z.number().optional(),
  operationAndMaintenance: z.number().optional(),
  otherCostofRevenue: z.number().optional(),
  explorationDevelopmentAndMineralPropertyLeaseExpenses: z.number().optional(),
});

export const fundamentalsTimeSeriesBalanceSheetResultSchema = z.object({
  date: z.string(),
  TYPE: z.literal("BALANCE_SHEET"),
  periodType: fundamentalsTimeSeriesPeriodSchema,
  netDebt: z.number().optional(),
  treasurySharesNumber: z.number().optional(),
  preferredSharesNumber: z.number().optional(),
  ordinarySharesNumber: z.number().optional(),
  shareIssued: z.number().optional(),
  totalDebt: z.number().optional(),
  tangibleBookValue: z.number().optional(),
  investedCapital: z.number().optional(),
  workingCapital: z.number().optional(),
  netTangibleAssets: z.number().optional(),
  capitalLeaseObligations: z.number().optional(),
  commonStockEquity: z.number().optional(),
  preferredStockEquity: z.number().optional(),
  totalCapitalization: z.number().optional(),
  totalEquityGrossMinorityInterest: z.number().optional(),
  minorityInterest: z.number().optional(),
  stockholdersEquity: z.number().optional(),
  otherEquityInterest: z.number().optional(),
  gainsLossesNotAffectingRetainedEarnings: z.number().optional(),
  otherEquityAdjustments: z.number().optional(),
  fixedAssetsRevaluationReserve: z.number().optional(),
  foreignCurrencyTranslationAdjustments: z.number().optional(),
  minimumPensionLiabilities: z.number().optional(),
  unrealizedGainLoss: z.number().optional(),
  treasuryStock: z.number().optional(),
  retainedEarnings: z.number().optional(),
  additionalPaidInCapital: z.number().optional(),
  capitalStock: z.number().optional(),
  otherCapitalStock: z.number().optional(),
  commonStock: z.number().optional(),
  preferredStock: z.number().optional(),
  totalPartnershipCapital: z.number().optional(),
  generalPartnershipCapital: z.number().optional(),
  limitedPartnershipCapital: z.number().optional(),
  totalLiabilitiesNetMinorityInterest: z.number().optional(),
  totalNonCurrentLiabilitiesNetMinorityInterest: z.number().optional(),
  otherNonCurrentLiabilities: z.number().optional(),
  liabilitiesHeldforSaleNonCurrent: z.number().optional(),
  restrictedCommonStock: z.number().optional(),
  preferredSecuritiesOutsideStockEquity: z.number().optional(),
  derivativeProductLiabilities: z.number().optional(),
  employeeBenefits: z.number().optional(),
  nonCurrentPensionAndOtherPostretirementBenefitPlans: z.number().optional(),
  nonCurrentAccruedExpenses: z.number().optional(),
  duetoRelatedPartiesNonCurrent: z.number().optional(),
  tradeandOtherPayablesNonCurrent: z.number().optional(),
  nonCurrentDeferredLiabilities: z.number().optional(),
  nonCurrentDeferredRevenue: z.number().optional(),
  nonCurrentDeferredTaxesLiabilities: z.number().optional(),
  longTermDebtAndCapitalLeaseObligation: z.number().optional(),
  longTermCapitalLeaseObligation: z.number().optional(),
  longTermDebt: z.number().optional(),
  longTermProvisions: z.number().optional(),
  currentLiabilities: z.number().optional(),
  otherCurrentLiabilities: z.number().optional(),
  currentDeferredLiabilities: z.number().optional(),
  currentDeferredRevenue: z.number().optional(),
  currentDeferredTaxesLiabilities: z.number().optional(),
  currentDebtAndCapitalLeaseObligation: z.number().optional(),
  currentCapitalLeaseObligation: z.number().optional(),
  currentDebt: z.number().optional(),
  otherCurrentBorrowings: z.number().optional(),
  lineOfCredit: z.number().optional(),
  commercialPaper: z.number().optional(),
  currentNotesPayable: z.number().optional(),
  pensionandOtherPostRetirementBenefitPlansCurrent: z.number().optional(),
  currentProvisions: z.number().optional(),
  payablesAndAccruedExpenses: z.number().optional(),
  currentAccruedExpenses: z.number().optional(),
  interestPayable: z.number().optional(),
  payables: z.number().optional(),
  otherPayable: z.number().optional(),
  duetoRelatedPartiesCurrent: z.number().optional(),
  dividendsPayable: z.number().optional(),
  totalTaxPayable: z.number().optional(),
  incomeTaxPayable: z.number().optional(),
  accountsPayable: z.number().optional(),
  totalAssets: z.number().optional(),
  totalNonCurrentAssets: z.number().optional(),
  otherNonCurrentAssets: z.number().optional(),
  definedPensionBenefit: z.number().optional(),
  nonCurrentPrepaidAssets: z.number().optional(),
  nonCurrentDeferredAssets: z.number().optional(),
  nonCurrentDeferredTaxesAssets: z.number().optional(),
  duefromRelatedPartiesNonCurrent: z.number().optional(),
  nonCurrentNoteReceivables: z.number().optional(),
  nonCurrentAccountsReceivable: z.number().optional(),
  financialAssets: z.number().optional(),
  investmentsAndAdvances: z.number().optional(),
  otherInvestments: z.number().optional(),
  investmentinFinancialAssets: z.number().optional(),
  heldToMaturitySecurities: z.number().optional(),
  availableForSaleSecurities: z.number().optional(),
  financialAssetsDesignatedasFairValueThroughProfitorLossTotal: z
    .number()
    .optional(),
  tradingSecurities: z.number().optional(),
  longTermEquityInvestment: z.number().optional(),
  investmentsinJointVenturesatCost: z.number().optional(),
  investmentsInOtherVenturesUnderEquityMethod: z.number().optional(),
  investmentsinAssociatesatCost: z.number().optional(),
  investmentsinSubsidiariesatCost: z.number().optional(),
  investmentProperties: z.number().optional(),
  goodwillAndOtherIntangibleAssets: z.number().optional(),
  otherIntangibleAssets: z.number().optional(),
  goodwill: z.number().optional(),
  netPPE: z.number().optional(),
  accumulatedDepreciation: z.number().optional(),
  grossPPE: z.number().optional(),
  leases: z.number().optional(),
  constructionInProgress: z.number().optional(),
  otherProperties: z.number().optional(),
  machineryFurnitureEquipment: z.number().optional(),
  buildingsAndImprovements: z.number().optional(),
  landAndImprovements: z.number().optional(),
  properties: z.number().optional(),
  currentAssets: z.number().optional(),
  otherCurrentAssets: z.number().optional(),
  hedgingAssetsCurrent: z.number().optional(),
  assetsHeldForSaleCurrent: z.number().optional(),
  currentDeferredAssets: z.number().optional(),
  currentDeferredTaxesAssets: z.number().optional(),
  restrictedCash: z.number().optional(),
  prepaidAssets: z.number().optional(),
  inventory: z.number().optional(),
  inventoriesAdjustmentsAllowances: z.number().optional(),
  otherInventories: z.number().optional(),
  finishedGoods: z.number().optional(),
  workInProcess: z.number().optional(),
  rawMaterials: z.number().optional(),
  receivables: z.number().optional(),
  receivablesAdjustmentsAllowances: z.number().optional(),
  otherReceivables: z.number().optional(),
  duefromRelatedPartiesCurrent: z.number().optional(),
  taxesReceivable: z.number().optional(),
  accruedInterestReceivable: z.number().optional(),
  notesReceivable: z.number().optional(),
  loansReceivable: z.number().optional(),
  accountsReceivable: z.number().optional(),
  allowanceForDoubtfulAccountsReceivable: z.number().optional(),
  grossAccountsReceivable: z.number().optional(),
  cashCashEquivalentsAndShortTermInvestments: z.number().optional(),
  otherShortTermInvestments: z.number().optional(),
  cashAndCashEquivalents: z.number().optional(),
  cashEquivalents: z.number().optional(),
  cashFinancial: z.number().optional(),
  otherLiabilities: z.number().optional(),
  liabilitiesOfDiscontinuedOperations: z.number().optional(),
  subordinatedLiabilities: z.number().optional(),
  advanceFromFederalHomeLoanBanks: z.number().optional(),
  tradingLiabilities: z.number().optional(),
  duetoRelatedParties: z.number().optional(),
  securitiesLoaned: z.number().optional(),
  federalFundsPurchasedAndSecuritiesSoldUnderAgreementToRepurchase: z
    .number()
    .optional(),
  financialInstrumentsSoldUnderAgreementsToRepurchase: z.number().optional(),
  federalFundsPurchased: z.number().optional(),
  totalDeposits: z.number().optional(),
  nonInterestBearingDeposits: z.number().optional(),
  interestBearingDepositsLiabilities: z.number().optional(),
  customerAccounts: z.number().optional(),
  depositsbyBank: z.number().optional(),
  otherAssets: z.number().optional(),
  assetsHeldForSale: z.number().optional(),
  deferredAssets: z.number().optional(),
  deferredTaxAssets: z.number().optional(),
  dueFromRelatedParties: z.number().optional(),
  allowanceForNotesReceivable: z.number().optional(),
  grossNotesReceivable: z.number().optional(),
  netLoan: z.number().optional(),
  unearnedIncome: z.number().optional(),
  allowanceForLoansAndLeaseLosses: z.number().optional(),
  grossLoan: z.number().optional(),
  otherLoanAssets: z.number().optional(),
  mortgageLoan: z.number().optional(),
  consumerLoan: z.number().optional(),
  commercialLoan: z.number().optional(),
  loansHeldForSale: z.number().optional(),
  derivativeAssets: z.number().optional(),
  securitiesAndInvestments: z.number().optional(),
  bankOwnedLifeInsurance: z.number().optional(),
  otherRealEstateOwned: z.number().optional(),
  foreclosedAssets: z.number().optional(),
  customerAcceptances: z.number().optional(),
  federalHomeLoanBankStock: z.number().optional(),
  securityBorrowed: z.number().optional(),
  cashCashEquivalentsAndFederalFundsSold: z.number().optional(),
  moneyMarketInvestments: z.number().optional(),
  federalFundsSoldAndSecuritiesPurchaseUnderAgreementsToResell: z
    .number()
    .optional(),
  securityAgreeToBeResell: z.number().optional(),
  federalFundsSold: z.number().optional(),
  restrictedCashAndInvestments: z.number().optional(),
  restrictedInvestments: z.number().optional(),
  restrictedCashAndCashEquivalents: z.number().optional(),
  interestBearingDepositsAssets: z.number().optional(),
  cashAndDueFromBanks: z.number().optional(),
  bankIndebtedness: z.number().optional(),
  mineralProperties: z.number().optional(),
  netPPEPurchaseAndSale: z.number().optional(),
  purchaseOfInvestment: z.number().optional(),
  investingCashFlow: z.number().optional(),
  grossProfit: z.number().optional(),
  cashFlowFromContinuingOperatingActivities: z.number().optional(),
  endCashPosition: z.number().optional(),
  netIncomeCommonStockholders: z.number().optional(),
  changeInAccountPayable: z.number().optional(),
  otherNonCashItems: z.number().optional(),
  cashDividendsPaid: z.number().optional(),
  dilutedAverageShares: z.number().optional(),
  repurchaseOfCapitalStock: z.number().optional(),
  EBITDA: z.number().optional(),
  stockBasedCompensation: z.number().optional(),
  commonStockDividendPaid: z.number().optional(),
  changeInPayable: z.number().optional(),
  costOfRevenue: z.number().optional(),
  operatingExpense: z.number().optional(),
  changeInInventory: z.number().optional(),
  normalizedIncome: z.number().optional(),
  netIncomeIncludingNoncontrollingInterests: z.number().optional(),
  netIncomeFromContinuingOperationNetMinorityInterest: z.number().optional(),
  reconciledCostOfRevenue: z.number().optional(),
  otherIncomeExpense: z.number().optional(),
  netInvestmentPurchaseAndSale: z.number().optional(),
  purchaseOfPPE: z.number().optional(),
  taxProvision: z.number().optional(),
  pretaxIncome: z.number().optional(),
  researchAndDevelopment: z.number().optional(),
  longTermDebtPayments: z.number().optional(),
  changeInReceivables: z.number().optional(),
  dilutedEPS: z.number().optional(),
  netIssuancePaymentsOfDebt: z.number().optional(),
  netShortTermDebtIssuance: z.number().optional(),
  depreciationAndAmortization: z.number().optional(),
  cashFlowFromContinuingInvestingActivities: z.number().optional(),
  beginningCashPosition: z.number().optional(),
  changesInCash: z.number().optional(),
  financingCashFlow: z.number().optional(),
  changeInOtherCurrentLiabilities: z.number().optional(),
  changeInWorkingCapital: z.number().optional(),
  operatingIncome: z.number().optional(),
  totalRevenue: z.number().optional(),
  netIncomeFromContinuingAndDiscontinuedOperation: z.number().optional(),
  operatingRevenue: z.number().optional(),
  changeInPayablesAndAccruedExpense: z.number().optional(),
  netCommonStockIssuance: z.number().optional(),
  commonStockPayments: z.number().optional(),
  EBIT: z.number().optional(),
  netOtherInvestingChanges: z.number().optional(),
  basicEPS: z.number().optional(),
  shortTermDebtPayments: z.number().optional(),
  sellingGeneralAndAdministration: z.number().optional(),
  netIncomeContinuousOperations: z.number().optional(),
  repaymentOfDebt: z.number().optional(),
  totalOperatingIncomeAsReported: z.number().optional(),
  normalizedEBITDA: z.number().optional(),
  capitalExpenditure: z.number().optional(),
  cashFlowFromContinuingFinancingActivities: z.number().optional(),
  netIncome: z.number().optional(),
  netOtherFinancingCharges: z.number().optional(),
  basicAverageShares: z.number().optional(),
  netLongTermDebtIssuance: z.number().optional(),
  depreciationAmortizationDepletion: z.number().optional(),
  operatingCashFlow: z.number().optional(),
  dilutedNIAvailtoComStockholders: z.number().optional(),
  netIncomeFromContinuingOperations: z.number().optional(),
  taxRateForCalcs: z.number().optional(),
  freeCashFlow: z.number().optional(),
  otherNonOperatingIncomeExpenses: z.number().optional(),
  changesInAccountReceivables: z.number().optional(),
  totalExpenses: z.number().optional(),
  changeInOtherCurrentAssets: z.number().optional(),
  reconciledDepreciation: z.number().optional(),
  incomeTaxPaidSupplementalData: z.number().optional(),
  saleOfInvestment: z.number().optional(),
  interestPaidSupplementalData: z.number().optional(),
  deferredTax: z.number().optional(),
  changeInOtherWorkingCapital: z.number().optional(),
  interestIncomeNonOperating: z.number().optional(),
  issuanceOfDebt: z.number().optional(),
  purchaseOfBusiness: z.number().optional(),
  longTermDebtIssuance: z.number().optional(),
  interestIncome: z.number().optional(),
  netInterestIncome: z.number().optional(),
  deferredIncomeTax: z.number().optional(),
  interestExpense: z.number().optional(),
  netNonOperatingInterestIncomeExpense: z.number().optional(),
  interestExpenseNonOperating: z.number().optional(),
  netBusinessPurchaseAndSale: z.number().optional(),
});

export const fundamentalsTimeSeriesCashFlowResultSchema = z.object({
  date: z.string(),
  TYPE: z.literal("CASH_FLOW"),
  periodType: fundamentalsTimeSeriesPeriodSchema,
  freeCashFlow: z.number().optional(),
  foreignSales: z.number().optional(),
  domesticSales: z.number().optional(),
  adjustedGeographySegmentData: z.number().optional(),
  repurchaseOfCapitalStock: z.number().optional(),
  repaymentOfDebt: z.number().optional(),
  issuanceOfDebt: z.number().optional(),
  issuanceOfCapitalStock: z.number().optional(),
  capitalExpenditure: z.number().optional(),
  interestPaidSupplementalData: z.number().optional(),
  incomeTaxPaidSupplementalData: z.number().optional(),
  endCashPosition: z.number().optional(),
  otherCashAdjustmentOutsideChangeinCash: z.number().optional(),
  beginningCashPosition: z.number().optional(),
  effectOfExchangeRateChanges: z.number().optional(),
  changesInCash: z.number().optional(),
  otherCashAdjustmentInsideChangeinCash: z.number().optional(),
  cashFlowFromDiscontinuedOperation: z.number().optional(),
  financingCashFlow: z.number().optional(),
  cashFromDiscontinuedFinancingActivities: z.number().optional(),
  cashFlowFromContinuingFinancingActivities: z.number().optional(),
  netOtherFinancingCharges: z.number().optional(),
  interestPaidCFF: z.number().optional(),
  proceedsFromStockOptionExercised: z.number().optional(),
  cashDividendsPaid: z.number().optional(),
  preferredStockDividendPaid: z.number().optional(),
  commonStockDividendPaid: z.number().optional(),
  netPreferredStockIssuance: z.number().optional(),
  preferredStockPayments: z.number().optional(),
  preferredStockIssuance: z.number().optional(),
  netCommonStockIssuance: z.number().optional(),
  commonStockPayments: z.number().optional(),
  commonStockIssuance: z.number().optional(),
  netIssuancePaymentsOfDebt: z.number().optional(),
  netShortTermDebtIssuance: z.number().optional(),
  shortTermDebtPayments: z.number().optional(),
  shortTermDebtIssuance: z.number().optional(),
  netLongTermDebtIssuance: z.number().optional(),
  longTermDebtPayments: z.number().optional(),
  longTermDebtIssuance: z.number().optional(),
  investingCashFlow: z.number().optional(),
  cashFromDiscontinuedInvestingActivities: z.number().optional(),
  cashFlowFromContinuingInvestingActivities: z.number().optional(),
  netOtherInvestingChanges: z.number().optional(),
  interestReceivedCFI: z.number().optional(),
  dividendsReceivedCFI: z.number().optional(),
  netInvestmentPurchaseAndSale: z.number().optional(),
  saleOfInvestment: z.number().optional(),
  purchaseOfInvestment: z.number().optional(),
  netInvestmentPropertiesPurchaseAndSale: z.number().optional(),
  saleOfInvestmentProperties: z.number().optional(),
  purchaseOfInvestmentProperties: z.number().optional(),
  netBusinessPurchaseAndSale: z.number().optional(),
  saleOfBusiness: z.number().optional(),
  purchaseOfBusiness: z.number().optional(),
  netIntangiblesPurchaseAndSale: z.number().optional(),
  saleOfIntangibles: z.number().optional(),
  purchaseOfIntangibles: z.number().optional(),
  netPPEPurchaseAndSale: z.number().optional(),
  saleOfPPE: z.number().optional(),
  purchaseOfPPE: z.number().optional(),
  capitalExpenditureReported: z.number().optional(),
  operatingCashFlow: z.number().optional(),
  cashFromDiscontinuedOperatingActivities: z.number().optional(),
  cashFlowFromContinuingOperatingActivities: z.number().optional(),
  taxesRefundPaid: z.number().optional(),
  interestReceivedCFO: z.number().optional(),
  interestPaidCFO: z.number().optional(),
  dividendReceivedCFO: z.number().optional(),
  dividendPaidCFO: z.number().optional(),
  changeInWorkingCapital: z.number().optional(),
  changeInOtherWorkingCapital: z.number().optional(),
  changeInOtherCurrentLiabilities: z.number().optional(),
  changeInOtherCurrentAssets: z.number().optional(),
  changeInPayablesAndAccruedExpense: z.number().optional(),
  changeInAccruedExpense: z.number().optional(),
  changeInInterestPayable: z.number().optional(),
  changeInPayable: z.number().optional(),
  changeInDividendPayable: z.number().optional(),
  changeInAccountPayable: z.number().optional(),
  changeInTaxPayable: z.number().optional(),
  changeInIncomeTaxPayable: z.number().optional(),
  changeInPrepaidAssets: z.number().optional(),
  changeInInventory: z.number().optional(),
  changeInReceivables: z.number().optional(),
  changesInAccountReceivables: z.number().optional(),
  otherNonCashItems: z.number().optional(),
  excessTaxBenefitFromStockBasedCompensation: z.number().optional(),
  stockBasedCompensation: z.number().optional(),
  unrealizedGainLossOnInvestmentSecurities: z.number().optional(),
  provisionandWriteOffofAssets: z.number().optional(),
  assetImpairmentCharge: z.number().optional(),
  amortizationOfSecurities: z.number().optional(),
  deferredTax: z.number().optional(),
  deferredIncomeTax: z.number().optional(),
  depletion: z.number().optional(),
  depreciationAndAmortization: z.number().optional(),
  amortizationCashFlow: z.number().optional(),
  amortizationOfIntangibles: z.number().optional(),
  depreciation: z.number().optional(),
  operatingGainsLosses: z.number().optional(),
  pensionAndEmployeeBenefitExpense: z.number().optional(),
  earningsLossesFromEquityInvestments: z.number().optional(),
  gainLossOnInvestmentSecurities: z.number().optional(),
  netForeignCurrencyExchangeGainLoss: z.number().optional(),
  gainLossOnSaleOfPPE: z.number().optional(),
  gainLossOnSaleOfBusiness: z.number().optional(),
  netIncomeFromContinuingOperations: z.number().optional(),
  cashFlowsfromusedinOperatingActivitiesDirect: z.number().optional(),
  taxesRefundPaidDirect: z.number().optional(),
  interestReceivedDirect: z.number().optional(),
  interestPaidDirect: z.number().optional(),
  dividendsReceivedDirect: z.number().optional(),
  dividendsPaidDirect: z.number().optional(),
  classesofCashPayments: z.number().optional(),
  otherCashPaymentsfromOperatingActivities: z.number().optional(),
  paymentsonBehalfofEmployees: z.number().optional(),
  paymentstoSuppliersforGoodsandServices: z.number().optional(),
  classesofCashReceiptsfromOperatingActivities: z.number().optional(),
  otherCashReceiptsfromOperatingActivities: z.number().optional(),
  receiptsfromGovernmentGrants: z.number().optional(),
  receiptsfromCustomers: z.number().optional(),
  increaseDecreaseInDeposit: z.number().optional(),
  changeInFederalFundsAndSecuritiesSoldForRepurchase: z.number().optional(),
  netProceedsPaymentForLoan: z.number().optional(),
  paymentForLoans: z.number().optional(),
  proceedsFromLoans: z.number().optional(),
  proceedsPaymentInInterestBearingDepositsInBank: z.number().optional(),
  increaseinInterestBearingDepositsinBank: z.number().optional(),
  decreaseinInterestBearingDepositsinBank: z.number().optional(),
  proceedsPaymentFederalFundsSoldAndSecuritiesPurchasedUnderAgreementToResell: z
    .number()
    .optional(),
  changeInLoans: z.number().optional(),
  changeInDeferredCharges: z.number().optional(),
  provisionForLoanLeaseAndOtherLosses: z.number().optional(),
  amortizationOfFinancingCostsAndDiscounts: z.number().optional(),
  depreciationAmortizationDepletion: z.number().optional(),
  realizedGainLossOnSaleOfLoansAndLease: z.number().optional(),
  allTaxesPaid: z.number().optional(),
  interestandCommissionPaid: z.number().optional(),
  cashPaymentsforLoans: z.number().optional(),
  cashPaymentsforDepositsbyBanksandCustomers: z.number().optional(),
  cashReceiptsfromFeesandCommissions: z.number().optional(),
  cashReceiptsfromSecuritiesRelatedActivities: z.number().optional(),
  cashReceiptsfromLoans: z.number().optional(),
  cashReceiptsfromDepositsbyBanksandCustomers: z.number().optional(),
  cashReceiptsfromTaxRefunds: z.number().optional(),
  AmortizationAmortizationCashFlow: z.number().optional(),
});

export const fundamentalsTimeSeriesAllResultSchema =
  fundamentalsTimeSeriesFinancialsResultSchema
    .omit({ TYPE: true })
    .and(fundamentalsTimeSeriesBalanceSheetResultSchema.omit({ TYPE: true }))
    .and(fundamentalsTimeSeriesCashFlowResultSchema.omit({ TYPE: true }))
    .and(
      z.object({
        TYPE: z.literal("ALL"),
      })
    );

export const fundamentalsTimeSeriesResultSchema = z.union([
  fundamentalsTimeSeriesBalanceSheetResultSchema,
  fundamentalsTimeSeriesCashFlowResultSchema,
  fundamentalsTimeSeriesFinancialsResultSchema,
  fundamentalsTimeSeriesAllResultSchema,
]);

export const fundamentalsTimeSeriesResultsSchema = z.array(
  fundamentalsTimeSeriesResultSchema
);

export const fundamentalsTimeSeriesOptionsSchema = z.object({
  period1: z.union([z.string(), z.number(), z.string()]),
  period2: z.union([z.string(), z.number(), z.string()]).optional(),
  type: z.string().optional(),
  merge: z.boolean().optional(),
  padTimeSeries: z.boolean().optional(),
  lang: z.string().optional(),
  region: z.string().optional(),
  module: z.string(),
});

export const assetProfileSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    address1: z.string().optional(),
    address2: z.string().optional(),
    address3: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    country: z.string().optional(),
    phone: z.string().optional(),
    fax: z.string().optional(),
    website: z.string().optional(),
    industry: z.string().optional(),
    industryDisp: z.string().optional(),
    industryKey: z.string().optional(),
    industrySymbol: z.string().optional(),
    sector: z.string().optional(),
    sectorDisp: z.string().optional(),
    sectorKey: z.string().optional(),
    longBusinessSummary: z.string().optional(),
    fullTimeEmployees: z.number().optional(),
    companyOfficers: z.array(companyOfficerSchema),
    auditRisk: z.number().optional(),
    boardRisk: z.number().optional(),
    compensationRisk: z.number().optional(),
    shareHolderRightsRisk: z.number().optional(),
    overallRisk: z.number().optional(),
    governanceEpochDate: z.string().optional(),
    compensationAsOfEpochDate: z.string().optional(),
    name: z.string().optional(),
    startDate: z.string().optional(),
    description: z.string().optional(),
    twitter: z.string().optional(),
    irWebsite: z.string().optional(),
    executiveTeam: z.array(z.unknown()).optional(),
  })
);

export const balanceSheetHistorySchema = z.record(z.string(), z.unknown()).and(
  z.object({
    balanceSheetStatements: z.array(balanceSheetStatementSchema),
    maxAge: z.number(),
  })
);

export const calendarEventsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    earnings: calendarEventsEarningsSchema,
    exDividendDate: z.string().optional(),
    dividendDate: z.string().optional(),
  })
);

export const cashflowStatementHistorySchema = z.object({
  cashflowStatements: z.array(cashflowStatementSchema),
  maxAge: z.number(),
});

export const earningsHistorySchema = z.record(z.string(), z.unknown()).and(
  z.object({
    history: z.array(earningsHistoryHistorySchema),
    maxAge: z.number(),
  })
);

export const ownershipSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    ownershipList: z.array(ownershipListSchema),
  })
);

export const incomeStatementHistorySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      incomeStatementHistory: z.array(incomeStatementHistoryElementSchema),
      maxAge: z.number(),
    })
  );

export const indexTrendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    symbol: z.string(),
    peRatio: z.number().optional(),
    pegRatio: z.number().optional(),
    estimates: z.array(estimateSchema),
  })
);

export const recommendationTrendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    trend: z.array(recommendationTrendTrendSchema),
    maxAge: z.number(),
  })
);

export const topHoldingsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    stockPosition: z.number().optional(),
    bondPosition: z.number().optional(),
    holdings: z.array(topHoldingsHoldingSchema),
    equityHoldings: topHoldingsEquityHoldingsSchema,
    bondHoldings: z.record(z.string(), z.any()),
    bondRatings: z.array(topHoldingsBondRatingSchema),
    sectorWeightings: z.array(topHoldingsSectorWeightingSchema),
    cashPosition: z.number().optional(),
    otherPosition: z.number().optional(),
    preferredPosition: z.number().optional(),
    convertiblePosition: z.number().optional(),
  })
);

export const earningsChartSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    quarterly: z.array(earningsChartQuarterlySchema),
    currentQuarterEstimate: z.number().optional(),
    currentQuarterEstimateDate: z.string().optional(),
    currentQuarterEstimateYear: z.number().optional(),
    earningsDate: z.array(z.string()),
    isEarningsDateEstimate: z.boolean().optional(),
  })
);

export const financialsChartSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    yearly: z.array(yearlySchema),
    quarterly: z.array(financialsChartQuarterlySchema),
  })
);

export const earningsTrendTrendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    period: z.string(),
    endDate: z.string().nullable(),
    growth: z.number().nullable(),
    earningsEstimate: earningsEstimateSchema,
    revenueEstimate: revenueEstimateSchema,
    epsTrend: epsTrendSchema,
    epsRevisions: epsRevisionsSchema,
  })
);

export const fundPerformanceReturnsSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      returns: z.array(fundPerformanceReturnsRowSchema),
      returnsCat: z.array(fundPerformanceReturnsRowSchema).optional(),
    })
  );

export const fundPerformanceRiskOverviewStatsSchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      riskStatistics: z.array(fundPerformanceRiskOverviewStatsRowSchema),
      riskRating: z.number().optional(),
    })
  );

export const holderSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    name: z.string(),
    relation: z.union([relationSchema, z.string()]),
    url: z.string(),
    transactionDescription: z.string(),
    latestTransDate: z.string(),
    positionDirect: z.number().optional(),
    positionDirectDate: z.string().optional(),
    positionIndirect: z.number().optional(),
    positionIndirectDate: z.string().optional(),
    positionSummaryDate: z.string().optional(),
  })
);

export const transactionSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    shares: z.number(),
    filerUrl: z.string(),
    transactionText: z.string(),
    filerName: z.string(),
    filerRelation: z.union([relationSchema, z.string()]),
    moneyText: z.string(),
    startDate: z.string(),
    ownership: z.union([ownershipEnumSchema, z.string()]),
    value: z.number().optional(),
  })
);

export const filingSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    date: z.string(),
    epochDate: z.string(),
    type: filingTypeSchema,
    title: z.string(),
    edgarUrl: z.string(),
    maxAge: z.number(),
    url: z.string().optional(),
    exhibits: z
      .array(
        z.object({
          type: z.string(),
          url: z.string(),
          downloadUrl: z.string().optional(),
        })
      )
      .optional(),
  })
);

export const upgradeDowngradeHistoryHistorySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      epochGradeDate: z.string(),
      firm: z.string(),
      toGrade: gradeSchema,
      fromGrade: gradeSchema.optional(),
      action: actionSchema,
    })
  );

export const quoteSummaryEarningsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    earningsChart: earningsChartSchema,
    financialsChart: financialsChartSchema,
    financialCurrency: z.string().optional(),
  })
);

export const earningsTrendSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    trend: z.array(earningsTrendTrendSchema),
    maxAge: z.number(),
  })
);

export const fundPerformanceSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    maxAge: z.number(),
    loadAdjustedReturns: periodRangeSchema.optional(),
    rankInCategory: periodRangeSchema.optional(),
    performanceOverview: fundPerformancePerformanceOverviewSchema,
    performanceOverviewCat: fundPerformancePerformanceOverviewCatSchema,
    trailingReturns: fundPerformanceTrailingReturnsSchema,
    trailingReturnsNav: fundPerformanceTrailingReturnsSchema,
    trailingReturnsCat: fundPerformanceTrailingReturnsSchema,
    annualTotalReturns: fundPerformanceReturnsSchema,
    pastQuarterlyReturns: fundPerformanceReturnsSchema,
    riskOverviewStatistics: fundPerformanceRiskOverviewStatsSchema,
    riskOverviewStatisticsCat: fundPerformanceRiskOverviewStatsCatSchema,
    fundCategoryName: z.string().optional(),
  })
);

export const holdersSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    holders: z.array(holderSchema),
    maxAge: z.number(),
  })
);

export const insiderTransactionsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    transactions: z.array(transactionSchema),
    maxAge: z.number(),
  })
);

export const secFilingsSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    filings: z.array(filingSchema),
    maxAge: z.number(),
  })
);

export const upgradeDowngradeHistorySchema = z
  .record(z.string(), z.unknown())
  .and(
    z.object({
      history: z.array(upgradeDowngradeHistoryHistorySchema),
      maxAge: z.number(),
    })
  );

// Main schemas (manually created as ts-to-zod didn't generate them)
export const quoteSummaryResultSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    assetProfile: assetProfileSchema.optional(),
    balanceSheetHistory: balanceSheetHistorySchema.optional(),
    balanceSheetHistoryQuarterly: balanceSheetHistorySchema.optional(),
    calendarEvents: calendarEventsSchema.optional(),
    cashflowStatementHistory: cashflowStatementHistorySchema.optional(),
    cashflowStatementHistoryQuarterly:
      cashflowStatementHistorySchema.optional(),
    defaultKeyStatistics: defaultKeyStatisticsSchema.optional(),
    earnings: quoteSummaryEarningsSchema.optional(),
    earningsHistory: earningsHistorySchema.optional(),
    earningsTrend: earningsTrendSchema.optional(),
    financialData: financialDataSchema.optional(),
    fundOwnership: ownershipSchema.optional(),
    fundPerformance: fundPerformanceSchema.optional(),
    fundProfile: fundProfileSchema.optional(),
    incomeStatementHistory: incomeStatementHistorySchema.optional(),
    incomeStatementHistoryQuarterly: incomeStatementHistorySchema.optional(),
    indexTrend: indexTrendSchema.optional(),
    industryTrend: trendSchema.optional(),
    insiderHolders: holdersSchema.optional(),
    insiderTransactions: insiderTransactionsSchema.optional(),
    institutionOwnership: ownershipSchema.optional(),
    majorDirectHolders: holdersSchema.optional(),
    majorHoldersBreakdown: majorHoldersBreakdownSchema.optional(),
    netSharePurchaseActivity: netSharePurchaseActivitySchema.optional(),
    price: priceSchema.optional(),
    quoteType: quoteTypeSchema.optional(),
    recommendationTrend: recommendationTrendSchema.optional(),
    secFilings: secFilingsSchema.optional(),
    sectorTrend: trendSchema.optional(),
    summaryDetail: summaryDetailSchema.optional(),
    summaryProfile: summaryProfileSchema.optional(),
    topHoldings: topHoldingsSchema.optional(),
    upgradeDowngradeHistory: upgradeDowngradeHistorySchema.optional(),
  })
);

export const insightsResultSchema = z.record(z.string(), z.unknown()).and(
  z.object({
    symbol: z.string(),
    instrumentInfo: z.any().optional(),
    companySnapshot: z.any().optional(),
    recommendation: z.any().optional(),
    events: z.array(z.any()).optional(),
    reports: z.array(z.any()).optional(),
    sigDevs: z.array(z.any()),
    upsell: z.any().optional(),
    upsellSearchDD: z.any().optional(),
    secReports: z.array(z.any()).optional(),
  })
);

export const chartResultArraySchema = z.array(
  z
    .object({
      date: z.number(),
      open: z.number().nullable().optional(),
      high: z.number().nullable().optional(),
      low: z.number().nullable().optional(),
      close: z.number().nullable().optional(),
      volume: z.number().nullable().optional(),
    })
    .catchall(z.unknown())
);

// Export with PascalCase names for consistency with type names
export const QuoteSummaryResultSchema = quoteSummaryResultSchema;
export const InsightsResultSchema = insightsResultSchema;
export const ChartResultArraySchema = chartResultArraySchema;
export const FundamentalsTimeSeriesResultSchema =
  fundamentalsTimeSeriesResultSchema;
export const FundamentalsTimeSeriesResultsSchema =
  fundamentalsTimeSeriesResultsSchema;
