#!/usr/bin/env tsx
/**
 * Script to generate Zod schemas from Yahoo Finance TypeScript types
 * Run with: pnpm generate:schemas
 */

import { execSync } from "child_process";

const inputFile = "lib/models/yahoo-finance-types.ts";
const outputFile = "lib/models/yahoo-finance-schemas.ts";

console.log("🔄 Generating Zod schemas from TypeScript types...");
console.log(`📥 Input: ${inputFile}`);
console.log(`📤 Output: ${outputFile}`);

try {
  // Use ts-to-zod CLI via pnpm exec to avoid npm warnings
  // Suppress npm warnings by unsetting problematic env vars
  const env = {
    ...process.env,
    npm_config_globalconfig: undefined,
    npm_config_verify_deps_before_run: undefined,
    npm_config__jsr_registry: undefined,
  };

  execSync(`pnpm exec ts-to-zod "${inputFile}" "${outputFile}"`, {
    stdio: "inherit",
    env,
  });

  // Read the generated file and add a header comment + PascalCase exports
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const fs = require("fs");
  let generatedContent = fs.readFileSync(outputFile, "utf-8");

  const header = `/**
 * This file is auto-generated by scripts/generate-yahoo-finance-schemas.ts
 * DO NOT EDIT MANUALLY - Run 'pnpm generate:schemas' to regenerate
 * 
 * Generated from: lib/models/yahoo-finance-types.ts
 * Generated at: ${new Date().toISOString()}
 */

`;

  // Only add header if it's not already there
  if (!generatedContent.includes("auto-generated")) {
    generatedContent = header + generatedContent;
  } else {
    // Update the timestamp in the header
    generatedContent = generatedContent.replace(
      /Generated at: .*/,
      `Generated at: ${new Date().toISOString()}`
    );
  }

  // Check if main schemas exist, if not create them
  if (!generatedContent.includes("export const quoteSummaryResultSchema")) {
    // Main schemas weren't generated, create them manually
    generatedContent +=
      "\n// Main schemas (manually created as ts-to-zod didn't generate them)\n";
    generatedContent +=
      "export const quoteSummaryResultSchema = z.record(z.string(), z.unknown()).and(z.object({\n";
    generatedContent += "    assetProfile: assetProfileSchema.optional(),\n";
    generatedContent +=
      "    balanceSheetHistory: balanceSheetHistorySchema.optional(),\n";
    generatedContent +=
      "    balanceSheetHistoryQuarterly: balanceSheetHistorySchema.optional(),\n";
    generatedContent +=
      "    calendarEvents: calendarEventsSchema.optional(),\n";
    generatedContent +=
      "    cashflowStatementHistory: cashflowStatementHistorySchema.optional(),\n";
    generatedContent +=
      "    cashflowStatementHistoryQuarterly: cashflowStatementHistorySchema.optional(),\n";
    generatedContent +=
      "    defaultKeyStatistics: defaultKeyStatisticsSchema.optional(),\n";
    generatedContent +=
      "    earnings: quoteSummaryEarningsSchema.optional(),\n";
    generatedContent +=
      "    earningsHistory: earningsHistorySchema.optional(),\n";
    generatedContent += "    earningsTrend: earningsTrendSchema.optional(),\n";
    generatedContent += "    financialData: financialDataSchema.optional(),\n";
    generatedContent += "    fundOwnership: ownershipSchema.optional(),\n";
    generatedContent +=
      "    fundPerformance: fundPerformanceSchema.optional(),\n";
    generatedContent += "    fundProfile: fundProfileSchema.optional(),\n";
    generatedContent +=
      "    incomeStatementHistory: incomeStatementHistorySchema.optional(),\n";
    generatedContent +=
      "    incomeStatementHistoryQuarterly: incomeStatementHistorySchema.optional(),\n";
    generatedContent += "    indexTrend: indexTrendSchema.optional(),\n";
    generatedContent += "    industryTrend: trendSchema.optional(),\n";
    generatedContent += "    insiderHolders: holdersSchema.optional(),\n";
    generatedContent +=
      "    insiderTransactions: insiderTransactionsSchema.optional(),\n";
    generatedContent +=
      "    institutionOwnership: ownershipSchema.optional(),\n";
    generatedContent += "    majorDirectHolders: holdersSchema.optional(),\n";
    generatedContent +=
      "    majorHoldersBreakdown: majorHoldersBreakdownSchema.optional(),\n";
    generatedContent +=
      "    netSharePurchaseActivity: netSharePurchaseActivitySchema.optional(),\n";
    generatedContent += "    price: priceSchema.optional(),\n";
    generatedContent += "    quoteType: quoteTypeSchema.optional(),\n";
    generatedContent +=
      "    recommendationTrend: recommendationTrendSchema.optional(),\n";
    generatedContent += "    secFilings: secFilingsSchema.optional(),\n";
    generatedContent += "    sectorTrend: trendSchema.optional(),\n";
    generatedContent += "    summaryDetail: summaryDetailSchema.optional(),\n";
    generatedContent +=
      "    summaryProfile: summaryProfileSchema.optional(),\n";
    generatedContent += "    topHoldings: topHoldingsSchema.optional(),\n";
    generatedContent +=
      "    upgradeDowngradeHistory: upgradeDowngradeHistorySchema.optional(),\n";
    generatedContent += "}));\n\n";
  }

  // Check for insights and chart schemas
  if (!generatedContent.includes("export const insightsResultSchema")) {
    generatedContent +=
      "export const insightsResultSchema = z.record(z.string(), z.unknown()).and(z.object({\n";
    generatedContent += "    symbol: z.string(),\n";
    generatedContent += "    instrumentInfo: z.any().optional(),\n";
    generatedContent += "    companySnapshot: z.any().optional(),\n";
    generatedContent += "    recommendation: z.any().optional(),\n";
    generatedContent += "    events: z.array(z.any()).optional(),\n";
    generatedContent += "    reports: z.array(z.any()).optional(),\n";
    generatedContent += "    sigDevs: z.array(z.any()),\n";
    generatedContent += "    upsell: z.any().optional(),\n";
    generatedContent += "    upsellSearchDD: z.any().optional(),\n";
    generatedContent += "    secReports: z.array(z.any()).optional(),\n";
    generatedContent += "}));\n\n";
  }

  if (!generatedContent.includes("export const chartResultArraySchema")) {
    generatedContent +=
      "export const chartResultArraySchema = z.array(z.object({\n";
    generatedContent += "    date: z.number(),\n";
    generatedContent += "    open: z.number().nullable().optional(),\n";
    generatedContent += "    high: z.number().nullable().optional(),\n";
    generatedContent += "    low: z.number().nullable().optional(),\n";
    generatedContent += "    close: z.number().nullable().optional(),\n";
    generatedContent += "    volume: z.number().nullable().optional(),\n";
    generatedContent += "    [z.unknown()]: z.unknown(),\n";
    generatedContent += "}));\n\n";
  }

  // Check for fundamentalsTimeSeries schema
  if (
    !generatedContent.includes(
      "export const fundamentalsTimeSeriesResultSchema"
    )
  ) {
    // Check if specific result schemas exist, otherwise use z.any()
    const hasFinancialsSchema = generatedContent.includes(
      "fundamentalsTimeSeriesFinancialsResultSchema"
    );
    const hasBalanceSheetSchema = generatedContent.includes(
      "fundamentalsTimeSeriesBalanceSheetResultSchema"
    );
    const hasCashFlowSchema = generatedContent.includes(
      "fundamentalsTimeSeriesCashFlowResultSchema"
    );
    const hasAllSchema = generatedContent.includes(
      "fundamentalsTimeSeriesAllResultSchema"
    );

    if (
      hasFinancialsSchema &&
      hasBalanceSheetSchema &&
      hasCashFlowSchema &&
      hasAllSchema
    ) {
      generatedContent +=
        "export const fundamentalsTimeSeriesResultSchema = z.array(z.union([\n";
      generatedContent += "    fundamentalsTimeSeriesFinancialsResultSchema,\n";
      generatedContent +=
        "    fundamentalsTimeSeriesBalanceSheetResultSchema,\n";
      generatedContent += "    fundamentalsTimeSeriesCashFlowResultSchema,\n";
      generatedContent += "    fundamentalsTimeSeriesAllResultSchema,\n";
      generatedContent += "]));\n\n";
    } else {
      // Fallback to z.any() if specific schemas aren't available
      generatedContent +=
        "export const fundamentalsTimeSeriesResultSchema = z.array(z.any());\n\n";
    }
  }

  // Convert z.nativeEnum() to z.enum() for Zod v4 compatibility
  // This fixes deprecation warnings
  // Handle both "export const" and "export declare const" patterns
  generatedContent = generatedContent.replace(
    /export (declare )?const relationSchema = z\.(nativeEnum|enum)\(Relation\);/g,
    `export const relationSchema = z.enum([
    "Chairman of the Board",
    "Chief Executive Officer",
    "Chief Financial Officer",
    "Chief Operating Officer",
    "Chief Technology Officer",
    "Director",
    "Director (Independent)",
    "",
    "General Counsel",
    "Independent Non-Executive Director",
    "Officer",
    "President",
] as const);`
  );

  generatedContent = generatedContent.replace(
    /export (declare )?const ownershipEnumSchema = z\.(nativeEnum|enum)\(OwnershipEnum\);/g,
    `export const ownershipEnumSchema = z.enum(["D", "I"] as const);`
  );

  generatedContent = generatedContent.replace(
    /export (declare )?const gradeSchema = z\.(nativeEnum|enum)\(Grade\);/g,
    `export const gradeSchema = z.enum([
    "Accumulate",
    "Add",
    "Average",
    "Below Average",
    "Buy",
    "Conviction Buy",
    "",
    "Equal-Weight",
    "Fair Value",
    "Equal-weight",
    "Long-term Buy",
    "Hold",
    "Long-Term Buy",
    "Market Outperform",
    "Market Perform",
    "Mixed",
    "Negative",
    "Neutral",
    "In-Line",
    "Outperform",
    "Overweight",
    "Peer Perform",
    "Perform",
    "Positive",
    "Reduce",
    "Sector Outperform",
    "Sector Perform",
    "Sector Weight",
    "Sell",
    "Strong Buy",
    "Top Pick",
    "Underperform",
    "Underperformer",
    "Underweight",
    "Trim",
    "Above Average",
    "In-line",
    "Outperformer",
    "OVerweight",
    "Cautious",
    "Market Weight",
    "Sector Underperform",
    "Market Underperform",
    "Peer perform",
    "Gradually Accumulate",
    "Action List Buy",
    "Performer",
    "Sector Performer",
    "Speculative Buy",
    "Strong Sell",
    "Speculative Hold",
    "Not Rated",
    "Hold Neutral",
    "Developing",
    "buy",
    "HOld",
    "Trading Sell",
    "Tender",
    "market perform",
    "BUy",
] as const);`
  );

  generatedContent = generatedContent.replace(
    /export (declare )?const actionSchema = z\.(nativeEnum|enum)\(Action\);/g,
    `export const actionSchema = z.enum(["down", "init", "main", "reit", "up"] as const);`
  );

  // Remove unused enum imports
  generatedContent = generatedContent.replace(
    /import \{ Relation, OwnershipEnum, Grade, Action \} from "\.\/yahoo-finance-types";/g,
    ""
  );

  // Fix chart schema passthrough to catchall
  generatedContent = generatedContent.replace(
    /}\.passthrough\(\)/g,
    "}).catchall(z.unknown())"
  );

  // Fix invalid computed property syntax in chart schema
  generatedContent = generatedContent.replace(
    /\[z\.unknown\(\)\]: z\.unknown\(\),?\s*/g,
    ""
  );

  // Replace z.date() with z.string() for OpenAPI/JSON Schema compatibility
  // Dates in JSON are represented as ISO 8601 strings
  generatedContent = generatedContent.replace(/z\.date\(\)/g, "z.string()");
  // Add catchall to chart schema if it doesn't have one
  if (
    generatedContent.includes("chartResultArraySchema") &&
    !generatedContent.includes("chartResultArraySchema.*catchall")
  ) {
    generatedContent = generatedContent.replace(
      /(export const chartResultArraySchema = z\.array\(z\.object\(\{[^}]*volume: z\.number\(\)\.nullable\(\)\.optional\(\)[^}]*)\s*\}\)\);/g,
      "$1}).catchall(z.unknown()));"
    );
  }

  // Check if fundProfileSchema exists, if not create it
  if (!generatedContent.includes("export const fundProfileSchema")) {
    // Find where to insert it (after fundProfileBrokerageSchema)
    const fundProfileBrokerageMatch = generatedContent.match(
      /(export const fundProfileBrokerageSchema[^;]+;)/
    );
    if (fundProfileBrokerageMatch) {
      const insertPoint =
        generatedContent.indexOf(fundProfileBrokerageMatch[0]) +
        fundProfileBrokerageMatch[0].length;
      const fundProfileSchema = `

export const fundProfileSchema = z.record(z.string(), z.unknown()).and(z.object({
    maxAge: z.number(),
    styleBoxUrl: z.string().nullable().optional(),
    family: z.string().nullable(),
    categoryName: z.string().nullable(),
    legalType: z.string().nullable(),
    managementInfo: fundProfileManagementInfoSchema.optional(),
    feesExpensesInvestment: fundProfileFeesExpensesInvestmentSchema.optional(),
    feesExpensesInvestmentCat: z.record(z.string(), z.unknown()).and(z.object({
        projectionValuesCat: z.record(z.string(), z.any()),
    })).optional(),
    brokerages: z.array(fundProfileBrokerageSchema).optional(),
    initInvestment: z.number().optional(),
    initIraInvestment: z.number().optional(),
    initAipInvestment: z.number().optional(),
    subseqInvestment: z.number().optional(),
    subseqIraInvestment: z.number().optional(),
    subseqAipInvestment: z.number().optional(),
}));`;
      generatedContent =
        generatedContent.slice(0, insertPoint) +
        fundProfileSchema +
        generatedContent.slice(insertPoint);
    }
  }

  // Add PascalCase exports if they don't exist
  if (
    !generatedContent.includes(
      "QuoteSummaryResultSchema = quoteSummaryResultSchema"
    )
  ) {
    generatedContent +=
      "// Export with PascalCase names for consistency with type names\n";
    generatedContent +=
      "export const QuoteSummaryResultSchema = quoteSummaryResultSchema;\n";
    generatedContent +=
      "export const InsightsResultSchema = insightsResultSchema;\n";
    generatedContent +=
      "export const ChartResultArraySchema = chartResultArraySchema;\n";
    generatedContent +=
      "export const FundamentalsTimeSeriesResultSchema = fundamentalsTimeSeriesResultSchema;\n";
    // Also export the array version (FundamentalsTimeSeriesResults)
    if (generatedContent.includes("fundamentalsTimeSeriesResultsSchema")) {
      generatedContent +=
        "export const FundamentalsTimeSeriesResultsSchema = fundamentalsTimeSeriesResultsSchema;\n";
    }
  }

  fs.writeFileSync(outputFile, generatedContent, "utf-8");

  console.log("✅ Successfully generated Zod schemas!");
  console.log(`📄 Output written to: ${outputFile}`);
} catch (error) {
  console.error("❌ Error generating schemas:", error);
  process.exit(1);
}
